### ISSUE TITLE
Unable to view 2020 patches history datamine

### ISSUE THREAD

**Issue by komakitsu** [nORbDragon/e7vault-issues#16]
Hello, there seems to be an issue with viewing Patches history (datamine) year 2020. 
Upon clicking the 2020 tab, the 2020 list of patches do not show. The problem appears on all browsers tried (Edge, Chrome and Firefox).
As seen in image below, although query changes to 2020, the displayed patches are still 2021.
![Capture](https://user-images.githubusercontent.com/53848582/196500518-047323ed-ce26-4b49-bdaa-97a7fa518e36.PNG)
(And thank you so much for this convenient site ^-^)

**Comment by nORbDragon** [comment]
Auch. Yep, I changed some lines in wrong places when was Lua's release. Fixed.

Thanks for bug report. xD
