### ISSUE TITLE
Battle sprite/home screen sprite viewer

### ISSUE THREAD

**Issue by Perdanaeka** [nORbDragon/e7vault-issues#24]
Is it possible for the web to provide a battle/home screen sprite viewer version of the character, since there are /model image uploaded to the site. but if its to much of work for the website, maybe could you put the .json and .atlas file there? thankyou.
![14-belian-epic-seven-screenshot](https://user-images.githubusercontent.com/18210661/216760531-2f46990f-c874-4497-92e4-fc0d857e75e7.jpg)
![tto0j12swkc21](https://user-images.githubusercontent.com/18210661/216760612-db9b087a-6b80-4958-a73e-806cb741a28b.png)

**Comment by nORbDragon** [comment]
Well, let's say I give you these files. And what are you going to do with them? 

In the form in which they are now, they are not intended to be viewed and edited in the Spine. Jsons in "scsp" format there, "custom made" format for Epic Seven. Can be viewed by e7herder engine, but can't be opened/viewed by official programs like Spine, SkeletonViewer etc.

You can ~~steal~~ download **raw/bugged/with glitches** json files from https://www.norbdragon.com/e7vault/model-viewer.html

![image](https://user-images.githubusercontent.com/97672704/216902470-3091bee4-bcc6-4150-b22a-39e51d4911a9.png)

You are required to take the id from the address bar and put it in the link: ```https://www.norbdragon.com/e7vault/static/game/model/<id>.json```

Example links for Belian's files (json/atlas/png):
- https://www.norbdragon.com/e7vault/static/game/model/belian.json
- https://www.norbdragon.com/e7vault/static/game/model/belian.atlas
- https://www.norbdragon.com/e7vault/static/game/model/belian.png

**Comment by Perdanaeka** [comment]
Thankyou for the work really appreciate it, i tought that the battle sprite using the same version as their character because the newer one that didn't work with e7herder can be opened using SpineVew (ver. 4.1.09 i think)
![Screenshot (176)](https://user-images.githubusercontent.com/18210661/218560704-cbd25130-343c-47be-83b2-5dd78aaf173e.png)
turn out it is using the scsp version, as for opening it i think i can using zklm web dump and boot up a local server so i can using the engine and overwrite existing character file because that's how i use to open old character like Luna which using that scsp version


![Screenshot (177)](https://user-images.githubusercontent.com/18210661/218566257-e3b3cd92-fd7a-4772-8570-35eaa1bba239.png)

now with your web i can use it without trouble, this is awsome building web is really hard and you make it just for fun

**Comment by Perdanaeka** [comment]
i suppose this can be closed now
